FROM node:20-alpine

WORKDIR /app

# Copy everything
COPY . .

# Install pnpm
RUN npm install -g pnpm@9.0.0

# Install dependencies
RUN pnpm install --frozen-lockfile

# Build HTTP backend
RUN pnpm --filter http-backend build

# Set working directory
WORKDIR /app/apps/http-backend

# Expose port
EXPOSE 3001

# Start
CMD ["node", "./dist/index.js"]
