FROM node:20-alpine

WORKDIR /app

# Copy everything
COPY . .

# Install pnpm
RUN npm install -g pnpm@9.0.0

# Install dependencies
RUN pnpm install --frozen-lockfile

# Build WS backend
RUN pnpm --filter ws-backend build

# Set working directory
WORKDIR /app/apps/ws-backend

# Expose port
EXPOSE 8080

# Start
CMD ["node", "./dist/index.js"]
